### ISSUE TITLE
LPC contains NaN or Infinity

### ISSUE THREAD

**Issue by XunChangqing** [ppwwyyxx/speaker-recognition#1]
Hello，
  I've test the tool on my simple data set. When the gmm from sklearn is used, it raised the error:

Warning: failed to import fast-gmm, use gmm from scikit-learn instead
Label person_xcq has files data/person_xcq/2.wav,data/person_xcq/1.wav
Label person_wzw has files data/person_wzw/wzw3.wav,data/person_wzw/wzw2.wav,data/person_wzw/wzw1.wav
Label person_ffy has files data/person_ffy/ffy3.wav,data/person_ffy/ffy1.wav,data/person_ffy/ffy2.wav
Label person_lj has files data/person_lj/2.wav,data/person_lj/1.wav,data/person_lj/3.wav
Label person_czy has files data/person_czy/czy2.wav,data/person_czy/czy3.wav,data/person_czy/czy1.wav
Start training...
Traceback (most recent call last):
  File "./src/speaker-recognition.py", line 89, in <module>
    task_enroll(args.input, args.model)
  File "./src/speaker-recognition.py", line 73, in task_enroll
    m.train()
  File "/home/xcq/work/speaker-recognition/src/gui/interface.py", line 72, in train
    self.gmmset.fit_new(feats, name)
  File "/home/xcq/work/speaker-recognition/src/gui/skgmm.py", line 21, in fit_new
    gmm.fit(x)
  File "/usr/lib/python2.7/dist-packages/sklearn/mixture/gmm.py", line 437, in fit
    random_state=self.random_state).fit(X).cluster_centers_
  File "/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py", line 702, in fit
    X = self._check_fit_data(X)
  File "/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py", line 668, in _check_fit_data
    X = atleast2d_or_csr(X, dtype=np.float64)
  File "/usr/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 134, in atleast2d_or_csr
    "tocsr", force_all_finite)
  File "/usr/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 111, in _atleast2d_or_sparse
    force_all_finite=force_all_finite)
  File "/usr/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 93, in array2d
    _assert_all_finite(X_2d)
  File "/usr/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 27, in _assert_all_finite
    raise ValueError("Array contains NaN or infinity.")
ValueError: Array contains NaN or infinity.

  If I do make -C src/gmm, no error will be reported, but the result models contain NaN.

32
0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 0.03125 
28 1
-nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan 
-nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan -nan

  Finnally, I found that the LPC feature contains NaN. I modify the mix_feature in src/feature/__init__.py to use the mfcc only, then it works.
  I have upload the used simple dataset to my forked repos.

Thanks.

**Comment by ppwwyyxx** [comment]
Thanks. LPC do return NaN when given a long array full of zeros.
Commit abf6a0ad41 changed all NaN in the feature to zeros, which should work well with the classifier.
