### ISSUE TITLE
The program does not run

### ISSUE THREAD

**Issue by shirkhorshidi** [ppwwyyxx/speaker-recognition#12]
It gives the following error:

`No module named bob
Warning: failed to import Bob, will use a slower version of MFCC instead.
Traceback (most recent call last):
  File "C:/Users/User/Desktop/speaker-recognition-master/speaker-recognition-master/src/speaker-recognition.py", line 17, in <module>
    from gui.interface import ModelInterface
  File "C:\Users\User\Desktop\speaker-recognition-master\speaker-recognition-master\src\gui\interface.py", line 17, in <module>
    from filters.VAD import VAD
  File "C:\Users\User\Desktop\speaker-recognition-master\speaker-recognition-master\src\filters\VAD.py", line 7, in <module>
    from noisered import NoiseReduction
  File "C:\Users\User\Desktop\speaker-recognition-master\speaker-recognition-master\src\filters\noisered.py", line 13, in <module>
    from utils import monophonic
  File "C:\Users\User\Desktop\speaker-recognition-master\speaker-recognition-master\src\filters\utils.py", line 1
    ../gui/utils.py
    ^
SyntaxError: invalid syntax

Process finished with exit code 1`

**Comment by ppwwyyxx** [comment]
we didn't support windows

**Comment by shirkhorshidi** [comment]
I haven't noticed the restriction of the platform, many thanks for the reply.

**Comment by deveid** [comment]
it also gives that same error on ubuntu
