### ISSUE TITLE
Could you please clarify how to run the script?

### ISSUE THREAD

**Issue by ylz09** [ppwwyyxx/speaker-recognition#13]
First, your results seem pretty good. I have some problems hope you can help.

This command works fine:
make -C src/gmm

Then I run ./speaker-recognition.py, some errors occur
Traceback (most recent call last):
  File "./speaker-recognition.py", line 17, in <module>
    from gui.interface import ModelInterface
  File "/root/speaker-recognition/src/gui/interface.py", line 16, in <module>
    from feature import mix_feature
  File "/root/speaker-recognition/src/gui/feature/__init__.py", line 17, in <module>
    import LPC
  File "/root/speaker-recognition/src/gui/feature/LPC.py", line 9, in <module>
    from scikits.talkbox.linpred import levinson_lpc
  File "/usr/local/lib/python2.7/dist-packages/scikits/talkbox/__init__.py", line 3, in <module>
    from tools import *
  File "/usr/local/lib/python2.7/dist-packages/scikits/talkbox/tools/__init__.py", line 7, in <module>
    import cffilter
  File "numpy.pxd", line 30, in cffilter (scikits/talkbox/tools/src/cffilter.c:2795)
ValueError: numpy.dtype does not appear to be the correct type object

Do you have ever encounter such a problems? 
BTW how to open the GUI? THANKS

**Comment by ppwwyyxx** [comment]
If `python -c 'from scikits.talkbox.linpred import levinson_lpc'` gave you error, you should report bugs to [scikits.talkbox](https://github.com/cournape/talkbox)

**Comment by ylz09** [comment]
Thanks for your reply. 
I solved this problem. Because I updated the numpy after I installed the scikits.talkbox. 
So I reinstalled the scikits, then it works!
pip install --upgrade --force-reinstall  scikits.talkbox

**Comment by ylz09** [comment]
@ppwwyyxx could please send me a copy of test corpus or any suggestions for free databases ? Thanks!

**Comment by ppwwyyxx** [comment]
Sorry but we don't have our training dataset any more.

**Comment by gitrohini** [comment]
I have same problem .I try 
pip install --upgrade --force-reinstall scikits.talkbox
this gives me error 
Cannot uninstall 'scikits.talkbox'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
what should i do??any suggestion
