### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by richardpenner** [ppwwyyxx/speaker-recognition#17]
I'm seeing the following crash when trying to enroll:
```python
Traceback (most recent call last):
  File "./speaker-recognition.py", line 89, in <module>
    task_enroll(args.input, args.model)
  File "./speaker-recognition.py", line 71, in task_enroll
    m.enroll(label, fs, signal)
  File "/Users/richardpenner/Downloads/speaker-recognition-master/src/gui/interface.py", line 60, in enroll
    feat = mix_feature((fs, signal))
  File "/Users/richardpenner/Downloads/speaker-recognition-master/src/gui/feature/__init__.py", line 26, in mix_feature
    mfcc = MFCC.extract(tup)
  File "/Users/richardpenner/Downloads/speaker-recognition-master/src/gui/feature/MFCC.py", line 128, in extract
    ret = get_mfcc_extractor(fs, **kwargs).extract(signal)
  File "/Users/richardpenner/Downloads/speaker-recognition-master/src/gui/feature/MFCC.py", line 70, in extract
    feature = row_stack(feature)
  File "/Users/richardpenner/PROJECTS/miniconda2/envs/speaker3/lib/python2.7/site-packages/numpy/core/shape_base.py", line 230, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

Any ideas what might be wrong?

**Comment by ppwwyyxx** [comment]
What's the command you used? And could you `ls` the directory to show that you have the files?

**Comment by richardpenner** [comment]
The command I ran was:
```bash
./speaker-recognition.py -t enroll --input "./waves-enroll/*" --model model.out
```

and the contents of `./waves-enroll` is 2 directories: `ben` and `james`. Each of those 2 directories have hundreds of files named as, for example, 
```bash
B-10_00m_00s__00m_01s.mp3.wav
B-10_00m_01s__00m_02s.mp3.wav
B-10_00m_02s__00m_03s.mp3.wav
…
```

**Comment by ppwwyyxx** [comment]
The files look correct. Another reason is that some of your files may be too short. I just added a line in 593425851e to check this.

**Comment by richardpenner** [comment]
Thank you. I split the wav files into 1 second each, based on a comment you made somewhere, but now I wonder if you're creating 1s samples internally and the wav files can be longer?

**Comment by richardpenner** [comment]
You were correct – some of the files were too short. I was using 1 second waves based on a misunderstanding of something you wrote elsewhere. Using longer input waves is now working. Thank you!
