### ISSUE TITLE
version of bob libraries not known, undefined symbol: _ZN5boost9iostreams4zlib8deflatedE in libbob_core.so

### ISSUE THREAD

**Issue by code-player** [ppwwyyxx/speaker-recognition#26]
while installing bob.sp , following traceback occurs
Traceback (most recent call last):
      ```
File "<string>", line 1, in <module>
      File "/tmp/pip-build-kQnxpH/bob.sp/setup.py", line 45, in <module>
        bob_packages = bob_packages,
      File "/project/local/lib/python2.7/site-packages/bob/blitz/extension.py", line 52, in __init__
        BobExtension.__init__(self, *args, **kwargs)
      File "/project/local/lib/python2.7/site-packages/bob/extension/__init__.py", line 301, in __init__
        bob_includes, bob_libraries, bob_library_dirs, bob_macros = get_bob_libraries(self.bob_packages)
      File "/project/local/lib/python2.7/site-packages/bob/extension/__init__.py", line 193, in get_bob_libraries
        pkg = importlib.import_module(package)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/project/local/lib/python2.7/site-packages/bob/core/__init__.py", line 3, in <module>
        bob.extension.load_bob_library('bob.core', __file__)
      File "/project/local/lib/python2.7/site-packages/bob/extension/__init__.py", line 244, in load_bob_library
        ctypes.cdll.LoadLibrary(full_libname)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
        return self._dlltype(name)
      File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /project/local/lib/python2.7/site-packages/bob/core/libbob_core.so: undefined symbol: _ZN5boost9iostreams4zlib8deflatedE
```

**Comment by ppwwyyxx** [comment]
Maybe you can try installing boost first

**Comment by code-player** [comment]
yeah..i have installed boost first because bob.core has some of the dependencies over bob.So it's been installed already..

**Comment by ppwwyyxx** [comment]
I have no idea. This question is better suited to ask on the bob project.

**Comment by code-player** [comment]
i just want to know if same problem occured when you configured bob..?

**Comment by ppwwyyxx** [comment]
No. I never saw anything like this.

**Comment by code-player** [comment]
okay. anyways thank you for your time.
lets see if i can figure out something..
and just one more request..is there any contact like email or social media where i can reach out to you in case i got any problem understanding your project..

**Comment by ppwwyyxx** [comment]
Feel free to reopen or open new issues if you meet more problems.
