### ISSUE TITLE
NoiseFilter Not Initialized

### ISSUE THREAD

**Issue by rcbyron** [ppwwyyxx/speaker-recognition#4]
I'm trying to figure out how to use the GUI to see how this works. I want to train a user with multiple wave files.

Reproducible steps:
- Command Run (in Conda environment): `python gui.py`
- Go To Enrollment, fill in User Info, choose training wav file for Voice Enrollment
- Press "Train!"
- Press "Enroll!" and it gives this error: 

```
No module named ap
Warning: failed to import Bob, will use a slower version of MFCC instead.
Warning: failed to import fast-gmm, use gmm from scikit-learn instead
libpng warning: iCCP: known incorrect sRGB profile
avatar/doubao.jpg doubao
avatar/ltz.jpg ltz
avatar/wyx.jpg wyx
avatar/zxy.jpg zxy
Warning: failed to import gmmset. You may forget to compile gmm:
dlopen(/Users/conzor/Downloads/speaker-recognition-master/src/gui/gmm/python/../lib/pygmm.so, 6): image not found
Try running `make -C src/gmm` to compile gmm module.
But gmm from sklearn will work as well! Using it now!
Start training...
1.59740447998e-05  seconds
Traceback (most recent call last):
  File "gui.py", line 300, in do_enroll
    new_signal = self.backend.filter(*self.enrollWav)
  File "/Users/conzor/Downloads/speaker-recognition-master/src/gui/interface.py", line 47, in filter
    ret, intervals = self.vad.filter(fs, signal)
  File "/Users/conzor/Downloads/speaker-recognition-master/src/gui/filters/VAD.py", line 29, in filter
    raise Exception("NoiseFilter Not Initialized")
Exception: NoiseFilter Not Initialized
```

Cool project by the way!

Thanks in advance,
Connor

**Comment by ppwwyyxx** [comment]
You'll need to first initialize the background noise, by either "record background noise" or "load background noise".
