### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by wssgyyg** [ppwwyyxx/speaker-recognition#42]
Sorry to bother but I am doing my dissertation and need to take your code as an example.
Can you tell me what's wrong with this? I just enrolled myself and do conversation with myself, the problem occurred. I am so grateful if you can help me out!
#################################
Traceback (most recent call last):
  File "gui.py", line 188, in do_conversation
    signal = self.backend.filter(Main.FS, signal)
  File "/home/bruce/speaker-recognition-master/src/gui/interface.py", line 47, in filter
    ret, intervals = self.vad.filter(fs, signal)
  File "/home/bruce/speaker-recognition-master/src/gui/filters/VAD.py", line 33, in filter
    filtered, intervals = self.ltsd.filter(signal)
  File "/home/bruce/speaker-recognition-master/src/gui/filters/ltsd.py", line 54, in filter
    res, ltsds = self._get_ltsd().compute_with_noise(signal, self.noise_signal)
  File "/home/bruce/.local/lib/python2.7/site-packages/pyssp/vad/ltsd.py", line 70, in compute_with_noise
    return self._compute(signal)
  File "/home/bruce/.local/lib/python2.7/site-packages/pyssp/vad/ltsd.py", line 73, in _compute
    ltsds = sp.zeros(self._windownum)
ValueError: negative dimensions are not allowed

negative dimensions are not allowed
###################################

**Comment by wssgyyg** [comment]
Problem solved.
Just remove the 3rd argument of line 190 in gui.py
############
label = self.backend.predict(Main.FS, signal, True)
=> label = self.backend.predict(Main.FS, signal)
############
