### ISSUE TITLE
why can't I use fast-gmm?

### ISSUE THREAD

**Issue by TaowzzZ** [ppwwyyxx/speaker-recognition#50]
Hi,Yuxin Wu,
	Thank you for your excellent project.
	But I meet a problem.I hope I can get some hlep!
	When I was training my database,the system warned me that "`Warning: failed to import fast-gmm,use gmm from scikit-learn instead`".So I try to force to use fast-mm,error alerts appear as follow,
"
```
Traceback (most recent call last):
  File "./speaker-recognition.py", line 17, in <module>
    from gui.interface import ModelInterface
  File "/home/taowzzz/Downloads/speaker-recognition-master/src/gui/interface.py", line 20, in <module>
    from gmmset import GMMSetPyGMM as GMMSet
  File "/home/taowzzz/Downloads/speaker-recognition-master/src/gui/gmmset.py", line 14, in <module>
    from gmm.python.pygmm import GMM
  File "/home/taowzzz/Downloads/speaker-recognition-master/src/gui/gmm/python/pygmm.py", line 16, in <module>
    pygmm = cdll.LoadLibrary(path.join(dirname, '../lib/pygmm.so'))
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/taowzzz/Downloads/speaker-recognition-master/src/gui/gmm/python/../lib/pygmm.so: cannot open shared object file: No such file or directory
```
"
Could you please give me some advice?
Thank you!

**Comment by ppwwyyxx** [comment]
It's OK to use GMM from scikit-learn.

To use fast-gmm you need to compile it first, by `make -C src/gmm`

**Comment by TaowzzZ** [comment]
OK.

It's all right.

Thank you for your help!
