### ISSUE TITLE
unable to install dependencies

### ISSUE THREAD

**Issue by aishwaryaanegundi** [ppwwyyxx/speaker-recognition#69]
I am trying to install bob.blitz and gives the below error. If somebody have got similar error and have resolved please help    

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\dell\appdata\local\temp\pip-build-ww3uyx\bob.blitz\setup.py
", line 70, in <module>
        system_include_dirs=system_include_dirs,
      File "C:\Python27\lib\site-packages\bob\extension\__init__.py", line 356,
in __init__
        boost_pkg = boost(boost_req.replace('boost', '').strip())
      File "C:\Python27\lib\site-packages\bob\extension\boost.py", line 69, in _
_init__
        raise RuntimeError("could not find boost's `version.hpp' - have you inst
alled Boost on this machine?")
    RuntimeError: could not find boost's `version.hpp' - have you installed Boos
t on this machine?

**Comment by ppwwyyxx** [comment]
Windows is not supported
