### ISSUE TITLE
Error installing blitz

### ISSUE THREAD

**Issue by iamnimonic** [ppwwyyxx/speaker-recognition#72]
Ritiks-Air:~ QueenandI$ pip3 install bob.blitz
Collecting bob.blitz
  Using cached https://files.pythonhosted.org/packages/8c/42/c72dc24fcd7454e4b4a4e4d5cbbc237e3b3e5e7d6e281d44479e1890c39a/bob.blitz-2.0.15.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5n/t6_jrv0j3yzg4zj7_39jn3cw0000gn/T/pip-install-vuextloj/bob.blitz/setup.py", line 70, in <module>
        system_include_dirs=system_include_dirs,
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bob/extension/__init__.py", line 438, in __init__
        pkgs = check_packages(packages)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bob/extension/__init__.py", line 77, in check_packages
        p = pkgconfig(splitreq[0])
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bob/extension/pkgconfig.py", line 136, in __init__
        raise RuntimeError("pkg-config package `%s' was not found" % name)
    RuntimeError: pkg-config package `blitz' was not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5n/t6_jrv0j3yzg4zj7_39jn3cw0000gn/T/pip-install-vuextloj/bob.blitz/

**Comment by ppwwyyxx** [comment]
You need to install `blitz` before trying to install `bob.blitz`.
This is an issue with bob installation and is unrelated to this project. If you still encounter similar issues, you can open an issue in the bob project.

**Comment by iamnimonic** [comment]
been there done that. Thank-you for replying this fast tho👍.

**Comment by ppwwyyxx** [comment]
This is a question about blitz and not directly related to this project. Closing now and you can ask blitz community for help.
