### ISSUE TITLE
Gui Issues

### ISSUE THREAD

**Issue by deveid** [ppwwyyxx/speaker-recognition#86]
I get this error, what am I doing wrong?

No module named ap
Warning: failed to import Bob, will use a slower version of MFCC instead.
Traceback (most recent call last):
  File "speaker-recognition.py", line 17, in <module>
    from gui.interface import ModelInterface
  File "/home/david/Documents/speaker system/speaker-recognition-master/src/gui/interface.py", line 17, in <module>
    from filters.VAD import VAD
  File "/home/david/Documents/speaker system/speaker-recognition-master/src/filters/VAD.py", line 7, in <module>
    from noisered import NoiseReduction
  File "/home/david/Documents/speaker system/speaker-recognition-master/src/filters/noisered.py", line 13, in <module>
    from utils import monophonic
  File "/home/david/Documents/speaker system/speaker-recognition-master/src/filters/utils.py", line 1
    ../gui/utils.py
    ^
SyntaxError: invalid syntax

**Comment by vijender412** [comment]
> I get this error, what am I doing wrong?
> 
> No module named ap
> Warning: failed to import Bob, will use a slower version of MFCC instead.
> Traceback (most recent call last):
> File "speaker-recognition.py", line 17, in 
> from gui.interface import ModelInterface
> File "/home/david/Documents/speaker system/speaker-recognition-master/src/gui/interface.py", line 17, in 
> from filters.VAD import VAD
> File "/home/david/Documents/speaker system/speaker-recognition-master/src/filters/VAD.py", line 7, in 
> from noisered import NoiseReduction
> File "/home/david/Documents/speaker system/speaker-recognition-master/src/filters/noisered.py", line 13, in 
> from utils import monophonic
> File "/home/david/Documents/speaker system/speaker-recognition-master/src/filters/utils.py", line 1
> ../gui/utils.py
> ^
> SyntaxError: invalid syntax

Getting similar ERROR
